### ISSUE TITLE
'Download' button in 'recent rips' breaks for all urls containing "#"

### ISSUE THREAD

**Issue by 0ion9** [4pr0n/rip#12]
Pretty simple. Mainly occurs with imgur 'selections' like imgur.com/a/E49f1#6AG3G (I made that url up just now btw, so it probably doesn't point at anything.).

The exact effect seems to be that instead the download button pointing at rip.rarchives.com/#ESCAPED_URL (in my fictional example this would be rip.rarchives.com/#imgur.com%2Fa%2FE49f1 -- well, this is the form that seems to work, though the full escaped url would also include the (escaped) #6AG3G), it points at rip.rarchives.com/#ESCAPED_PART_OF_URL_AFTER_HASH (in my fictional example this would be rip.rarchives.com/#6AG3G).

Naturally this totally fails to recognize the url being sent in as anything valid.

**Comment by 4pr0n** [comment]
https://github.com/4pr0n/rip/commit/b871a1d17613431d4b63d6e614ad0cfb592763fc

Should be fixed. Be sure to shift+refresh to pull in the newest `rip.js` file
