### ISSUE TITLE
Support for DA Scraps

### ISSUE THREAD

**Issue by Gatekat** [4pr0n/rip#16]
I'd really love it if rip and zip on deviantart.com included the scraps tab, or at least the scraps could be entered as a URL. Currently entering the scraps URL only collects the main gallery.

**Comment by 4pr0n** [comment]
Please provide one or two sample URLs of "scraps"

**Comment by Gatekat** [comment]
http://alteride.deviantart.com/gallery/?catpath=scraps
http://alonzoemata.deviantart.com/gallery/?catpath=scraps
http://ferain.deviantart.com/gallery/?catpath=scraps

Despite being under the gallery URL, they do not download with the rest 
of the gallery.

**Comment by 4pr0n** [comment]
Attempted fix in https://github.com/4pr0n/rip/commit/41eeb0c11e971e197ab6cf1c14fee8207cd5e58a

pls confirm

**Comment by 4pr0n** [comment]
1 week with no response; closing.
