### ISSUE TITLE
Support sankakucomplex.com

### ISSUE THREAD

**Issue by 4pr0n** [4pr0n/rip#3]
from 9959 sent 5 days ago

I have a suggestion: Support for Sankaku chan! :D http://chan.sankakucomplex.com/

**Comment by 4pr0n** [comment]
If this request gets more support, I'll add it. I've never heard of this site and can't be bothered for honoring one-off requests.

**Comment by yestoc** [comment]
Sankaku Complex is a tag-based imageboard, results usually are in the thousands, not a good idea.

**Comment by piecesoftofu** [comment]
bump to fix
