### ISSUE TITLE
Support pichunter.com

### ISSUE THREAD

**Issue by 4pr0n** [4pr0n/rip#4]
from primoarnold sent 8 hours ago

I have a request. Is it possible to get the image ripper/zipper to work with http://society.pichunter.com/ The site requires a login but is free and is free of malware/spyware and adds as far as I can tell. Thank you in advance for your consideration in this.

**Comment by primoarnold** [comment]
As a sidenote I should clarify.  No username is necessary to view images.  However, sometimes to view a users account a username is necessary to see all they have posted.

**Comment by 4pr0n** [comment]
Added, seems to work on the sets I tried it out on

https://github.com/4pr0n/rip/commit/134a20eb82287ccc277ba6cdad2e98cbe7928ee0
